# application-eureka1.yml

eureka:
  instance:
    hostname: eureka1
  client:
    register-with-eureka: true
    fetch-registry: true
    # 1 连接2

    service-url:
      defaultZone: http://eureka2:2002/eureka